# Generated by Django 5.1.2 on 2024-12-17 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('package_name', models.CharField(max_length=200, unique=True)),
                ('points_value', models.IntegerField(default=10)),
                ('category', models.CharField(choices=[('GAMES', 'Games'), ('PRODUCTIVITY', 'Productivity'), ('SOCIAL', 'Social Media'), ('UTILITY', 'Utility'), ('OTHER', 'Other')], max_length=20)),
                ('app_icon', models.ImageField(blank=True, null=True, upload_to='android_app_icons/')),
                ('playstore_link', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAppTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='app_task_screenshots/')),
                ('points_earned', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='Androidapp.androidapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User App Task',
                'verbose_name_plural': 'User App Tasks',
                'unique_together': {('user', 'app')},
            },
        ),
    ]
