# Generated by Django 5.1.2 on 2024-12-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
